server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intuit_sentiments
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      default_schema: intuit_sentiments
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



